# Generated by Django 2.1.3 on 2019-01-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='s3file',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
